#!/usr/bin/env php
<?php

/**
 * Access point to project using the Terminal
 */

require __DIR__ . '/vendor/autoload.php';

use App\Commands\ImportData;
use App\Commands\RunWorker;
use Illuminate\Database\Capsule\Manager as DatabaseManager;
use Symfony\Component\Console\Application;

Dotenv\Dotenv::createImmutable(__DIR__)->load();

require_once __DIR__ . '/core/database/Connection.php';
require_once __DIR__ . '/core/migrations/migration.php';

(new Migration((new Connection(new DatabaseManager))->setup()))->migrate();
$app = (new Application);
$app->add(new ImportData);
$app->add(new RunWorker);
$app->run();
